// Medical constants for standardized data entry
export const EXISTING_CONDITIONS = [
  "Hypertension",
  "Diabetes Type 1",
  "Diabetes Type 2",
  "Heart Disease",
  "Coronary Artery Disease",
  "Tuberculosis",
  "Asthma",
  "COPD",
  "Gallstones",
  "Jaundice",
  "Hepatitis B",
  "Hepatitis C",
  "Paralysis",
  "Stroke",
  "Migraine",
  "Chronic Kidney Disease",
  "Thyroid Disorder",
  "Osteoporosis",
  "Depression",
  "Anxiety",
];

export const MAJOR_CONDITIONS = [
  "Cancer",
  "Epilepsy",
  "Rheumatoid Arthritis",
  "Osteoarthritis",
  "Peptic Ulcer",
  "Renal Disease",
  "Liver Disease",
  "Bipolar Disorder",
  "Schizophrenia",
  "Multiple Sclerosis",
  "Parkinson Disease",
  "Alzheimer Disease",
  "HIV/AIDS",
  "Lupus",
  "Crohn Disease",
];

export const COMMON_ALLERGIES = [
  "Penicillin",
  "Aspirin",
  "Sulfa Drugs",
  "Latex",
  "Peanuts",
  "Tree Nuts",
  "Shellfish",
  "Fish",
  "Milk/Dairy",
  "Eggs",
  "Soy",
  "Wheat/Gluten",
  "Dust Mites",
  "Pollen",
  "Animal Dander",
  "Mold",
  "Iodine",
  "Contrast Dye",
];

export const SURGERY_TYPES = [
  "Cardiac Bypass Surgery",
  "Angioplasty",
  "Gallbladder Surgery",
  "Appendectomy",
  "Hernia Repair",
  "Hip Replacement",
  "Knee Replacement",
  "Cataract Surgery",
  "Cesarean Section",
  "Hysterectomy",
  "Tonsillectomy",
  "Kidney Stone Removal",
  "Prostate Surgery",
  "Thyroid Surgery",
  "Spine Surgery",
];

export const IMMUNIZATIONS = [
  "COVID-19",
  "Influenza (Flu)",
  "Hepatitis B",
  "Hepatitis A",
  "Tetanus",
  "Pneumonia (Pneumococcal)",
  "Meningitis",
  "HPV",
  "Measles/Mumps/Rubella (MMR)",
  "Varicella (Chickenpox)",
  "Polio",
  "Tuberculosis (BCG)",
  "Typhoid",
  "Yellow Fever",
  "Rabies",
];

export const FAMILY_CONDITIONS = [
  "Heart Disease",
  "Diabetes",
  "Cancer",
  "Hypertension",
  "Stroke",
  "Mental Health Disorders",
  "Kidney Disease",
  "Liver Disease",
  "Thyroid Disorders",
  "Arthritis",
  "Osteoporosis",
  "Alzheimer Disease",
  "Epilepsy",
  "Asthma",
  "Allergies",
];
